from typing import Any

from .contracts import NarrativeReport


def build_fallback_narrative(evidence_pack: dict[str, Any]) -> NarrativeReport:
    """Generates a purely deterministic narrative using the existing structured reasons."""
    
    session_id = evidence_pack.get("session_id", "Unknown")
    verdict = evidence_pack.get("verdict", "REVIEW")
    reasons = evidence_pack.get("reasons", [])
    
    doc_type = evidence_pack.get("document_type") or "Document"
    intake = evidence_pack.get("intake_mode", "FILE")
    
    summary = f"This {doc_type.lower()} was submitted via {intake}. The automated forensic pipeline evaluated the document and reached a verdict of {verdict}."
    
    if not reasons:
        findings = "No specific reasons or adverse signals were recorded."
    else:
        findings = "Key automated findings:\n- " + "\n- ".join(reasons)
        
    action = f"Deterministic recommendation: {verdict}. (Generated by deterministic fallback engine due to LLM unavailability)."
    
    return NarrativeReport(
        session_id=session_id,
        verdict=verdict,
        summary_paragraph=summary,
        findings_paragraph=findings,
        action_paragraph=action,
        is_fallback=True
    )
