"""Tests for Layer 0 — intake doc-type classification + evidence sufficiency (ADR-004 §Layer-0).

The classifier must discriminate document families from real PDF text (CLAUDE.md §3.2 — would FAIL
against a constant), fall through to UNKNOWN on no/ambiguous evidence (never a coin-flip), and the
sufficiency assessment must honestly state that a lone un-pullable document is NOT, by itself, enough to
auto-approve (the input the Layer-7 brain uses to fail closed).
"""

from __future__ import annotations

import pytest

from app.contracts import AnalysisContext, Mode, SignalStatus
from intake.sufficiency import EvidenceSufficiency, IntakeSufficiencyAnalyzer, assess, classify_doc_type

pymupdf = pytest.importorskip("pymupdf")


def _pdf(text: str) -> bytes:
    """A one-page PDF carrying ``text`` wrapped inside the page (so it is fully extractable)."""
    doc = pymupdf.open()
    page = doc.new_page()
    rect = pymupdf.Rect(36, 36, page.rect.width - 36, page.rect.height - 36)
    page.insert_textbox(rect, text, fontsize=10)
    out = doc.tobytes()
    doc.close()
    return out


_STATEMENT_TEXT = (
    "ACCOUNT STATEMENT for the period 01/01/2024 to 31/03/2024. "
    "Opening Balance 10,000.00. Closing Balance 13,000.00. IFSC SBIN0001234. "
    "Value Date Description Withdrawal Deposit Balance. "
    "Salary credit, ATM withdrawal, NEFT deposit transactions are listed below across many rows "
    "so that the extractable text comfortably exceeds the digital-native threshold."
)
_SLIP_TEXT = (
    "SALARY SLIP for March 2024. Employee: Ramesh Kumar. Gross Earnings 50,000. Basic Pay 25,000. "
    "Total Deductions 8,000. Net Pay 42,000. This payslip is generated by the employer payroll system "
    "and lists all earnings and deductions for the month in adequate textual detail."
)


def _ctx(file_bytes: bytes, *, pull: bool = False, doc_type: str | None = None) -> AnalysisContext:
    return AnalysisContext(
        session_id="s",
        intake_mode=Mode.FILE,
        file_bytes=file_bytes,
        file_name="d.pdf",
        doc_type=doc_type,
        source_was_pullable=pull,
    )


# --- classifier (pure) ----------------------------------------------------------------------------


def test_classifier_discriminates_families():
    assert (
        classify_doc_type("Account Statement Opening Balance Closing Balance IFSC Value Date")
        == "BANK_STATEMENT"
    )
    assert classify_doc_type("Salary Slip Gross Earnings Total Deductions Net Pay Basic Pay") == "SALARY_SLIP"
    assert (
        classify_doc_type("Form 16 TDS Certificate certificate under section 203 Part A Part B") == "FORM16"
    )
    assert classify_doc_type("Income Tax Return ITR-V Acknowledgement Number Assessment Year") == "ITR"
    assert classify_doc_type("Sale Deed Sub-Registrar Survey Number Consideration Amount") == "LAND_DEED"


def test_classifier_unknown_on_no_or_ambiguous_match():
    assert classify_doc_type("a memo about lunch plans and the weather") == "UNKNOWN"
    assert classify_doc_type("") == "UNKNOWN"


# --- assessment -----------------------------------------------------------------------------------


def test_digital_statement_assessment():
    suff = assess(_ctx(_pdf(_STATEMENT_TEXT)))
    assert suff.doc_type == "BANK_STATEMENT"
    assert suff.quality == "digital_native"
    assert suff.evidence_level == "single-document"
    assert suff.achievable_confidence == "moderate"  # readable content, but no verifiable source
    assert suff.sufficient_for_auto_approve is False  # a lone unsigned doc is never enough by itself


def test_pullable_source_lifts_sufficiency():
    """The discriminating property: a verifiable source makes a strong verdict achievable."""
    no_pull = assess(_ctx(_pdf(_STATEMENT_TEXT), pull=False))
    pull = assess(_ctx(_pdf(_STATEMENT_TEXT), pull=True))
    assert no_pull.sufficient_for_auto_approve is False and no_pull.achievable_confidence == "moderate"
    assert pull.sufficient_for_auto_approve is True and pull.achievable_confidence == "high"


def test_salary_slip_classified():
    assert assess(_ctx(_pdf(_SLIP_TEXT))).doc_type == "SALARY_SLIP"


def test_scanned_pdf_is_low_confidence():
    """A PDF with negligible text layer (a scan) cannot be classified/assessed deterministically."""
    suff = assess(_ctx(_pdf("x")))
    assert suff.quality == "scanned" and suff.achievable_confidence == "low"


def test_image_upload_is_low_confidence():
    suff = assess(_ctx(b"\x89PNG\r\n\x1a\n not a pdf"))
    assert suff.quality == "image" and suff.sufficient_for_auto_approve is False


def test_client_doc_type_is_only_a_fallback():
    """A client-declared type fills in ONLY when the document text yields nothing (it can't override)."""
    # text says statement → wins over a misleading client hint
    assert assess(_ctx(_pdf(_STATEMENT_TEXT), doc_type="salary_slip")).doc_type == "BANK_STATEMENT"
    # unreadable text → the client hint is used as the fallback
    assert assess(_ctx(b"\x89PNG image", doc_type="form16")).doc_type == "FORM16"


# --- analyzer -------------------------------------------------------------------------------------


def test_analyzer_publishes_sufficiency_and_emits_pending_signal():
    az = IntakeSufficiencyAnalyzer()
    ctx = _ctx(_pdf(_STATEMENT_TEXT))
    sig = az.analyze(ctx)
    assert sig.status == SignalStatus.NOT_EVALUATED and sig.suspicion is None  # intake is not a tamper score
    assert isinstance(ctx.shared.get("sufficiency"), EvidenceSufficiency)
    assert sig.measurements["doc_type"] == "BANK_STATEMENT"
    assert sig.measurements["sufficient_for_auto_approve"] is False


def test_analyzer_runs_first_in_the_waterfall():
    from app.registry_assembly import build_registry

    chain = [a.name for a in build_registry().for_mode(Mode.FILE)]
    assert chain[0] == "intake_sufficiency"
