"""Deterministic entity extraction — the input to the cross-document consistency graph (ADR-003 #3).

The cross-document graph (``forensics/cross_document.py``) asks one question across a *bundle* of an
applicant's documents: do the identities agree? A forger can make each document individually
plausible, but keeping the **same** name / PAN / Aadhaar / account number coherent across a bank
statement, an ID, and a deed is much harder — and a mismatch is strong, explainable fraud evidence.

This module extracts the comparable fields from a single document's text. It is pure, deterministic
regex/checksum logic (CLAUDE.md §6 — real techniques only, no ML guessing):

  * **PAN**      — the Income-Tax PAN format ``AAAAA9999A`` (5 alpha, 4 digit, 1 alpha).
  * **Aadhaar**  — a 12-digit UIDAI number validated with the **real Verhoeff checksum** (UIDAI's
                   actual scheme). An Aadhaar-shaped number that FAILS Verhoeff is itself a forgery
                   signal, surfaced separately — never silently treated as a valid id.
  * **IFSC**     — ``AAAA0NNNNNN`` (4 alpha, a literal ``0``, 6 alnum) — the RBI bank-branch code.
  * **account**  — label-anchored ("A/c No", "Account Number") digit run (9–18 digits).
  * **name**     — label-anchored only ("Name", "Account Holder", "Customer"); we never *guess* a
                   name from arbitrary text — an unlabelled name stays ``None`` (honest, §3.1).
  * **dob**      — label-anchored date, normalised to ISO ``YYYY-MM-DD``.

Honest bound: names/addresses are noisy; extraction is conservative (label-anchored) so the
cross-document check trusts the *structured* identifiers (PAN/Aadhaar/IFSC/account/DOB) most and
treats names as a softer, fuzzy-matched corroborator.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from app.config import settings
from app.contracts import AnalysisContext, LayerSignal, Mode
from forensics.ocr import is_pdf

# --------------------------------------------------------------------------------------------------
# Verhoeff checksum (UIDAI Aadhaar's real validation scheme). Implemented from the canonical
# dihedral-group D5 multiplication table, the inverse table, and the base permutation P1; the rest of
# the permutation table is GENERATED by composition (avoids transcribing an 8-row table from memory,
# CLAUDE.md §6). The self-consistency test (generate a check digit -> validates; flip any digit ->
# fails) proves the implementation against Verhoeff's known single-digit-error guarantee.
# --------------------------------------------------------------------------------------------------

_D5_MULT = (
    (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
    (1, 2, 3, 4, 0, 6, 7, 8, 9, 5),
    (2, 3, 4, 0, 1, 7, 8, 9, 5, 6),
    (3, 4, 0, 1, 2, 8, 9, 5, 6, 7),
    (4, 0, 1, 2, 3, 9, 5, 6, 7, 8),
    (5, 9, 8, 7, 6, 0, 4, 3, 2, 1),
    (6, 5, 9, 8, 7, 1, 0, 4, 3, 2),
    (7, 6, 5, 9, 8, 2, 1, 0, 4, 3),
    (8, 7, 6, 5, 9, 3, 2, 1, 0, 4),
    (9, 8, 7, 6, 5, 4, 3, 2, 1, 0),
)
_INV = (0, 4, 3, 2, 1, 5, 6, 7, 8, 9)
_P1 = (1, 5, 7, 6, 2, 8, 3, 0, 9, 4)


def _perm(position: int, digit: int) -> int:
    """Verhoeff permutation p[(position mod 8)] applied to ``digit`` (P1 composed ``position`` times)."""
    d = digit
    for _ in range(position % 8):
        d = _P1[d]
    return d


def verhoeff_validate(number: str) -> bool:
    """True iff ``number`` (a digit string incl. its trailing check digit) satisfies Verhoeff."""
    if not number or not number.isdigit():
        return False
    c = 0
    for i, ch in enumerate(reversed(number)):
        c = _D5_MULT[c][_perm(i, int(ch))]
    return c == 0


def verhoeff_check_digit(number_without_check: str) -> int:
    """The check digit that makes ``number_without_check`` + digit a valid Verhoeff string."""
    c = 0
    for i, ch in enumerate(reversed(number_without_check)):
        c = _D5_MULT[c][_perm(i + 1, int(ch))]
    return _INV[c]


# --------------------------------------------------------------------------------------------------
# Field patterns and extraction.
# --------------------------------------------------------------------------------------------------

_PAN_RE = re.compile(r"\b([A-Z]{5}[0-9]{4}[A-Z])\b")
_IFSC_RE = re.compile(r"\b([A-Z]{4}0[A-Z0-9]{6})\b")
_AADHAAR_RE = re.compile(r"\b([2-9][0-9]{3}\s?[0-9]{4}\s?[0-9]{4})\b")
# Label-anchored fields (case-insensitive); capture the value to the end of the line.
_NAME_RE = re.compile(
    r"(?:account\s*holder|customer\s*name|holder\s*name|\bname)\s*[:\-]\s*([^\n\r]{2,60})",
    re.IGNORECASE,
)
_ACCOUNT_RE = re.compile(
    r"(?:a/?c\.?\s*(?:no\.?|number)?|account\s*(?:no\.?|number))\s*[:\-]?\s*([0-9][0-9\s-]{7,24}[0-9])",
    re.IGNORECASE,
)
_DOB_RE = re.compile(
    r"(?:date\s*of\s*birth|d\.?o\.?b\.?|born)\s*[:\-]?\s*"
    r"([0-3]?\d[\s./-][0-1]?\d[\s./-]\d{2,4}|\d{4}[\s./-][0-1]?\d[\s./-][0-3]?\d)",
    re.IGNORECASE,
)

_NAME_TITLES = re.compile(r"^(?:mr|mrs|ms|miss|shri|smt|dr|m/s)\.?\s+", re.IGNORECASE)
_NAME_TRAILING = re.compile(r"\s+(?:a/?c|account|pan|aadhaar|dob|address).*$", re.IGNORECASE)

# Aadhaar context markers. A bare 12-digit run is just as likely a bank Customer ID / CIF / account
# number as an Aadhaar; routing every such number through the UIDAI Verhoeff checksum produced false
# "forged Aadhaar" flags on genuine statements (KNOWN_ISSUES #5.2). We only treat a 12-digit number as
# an Aadhaar when it carries Aadhaar context: an Aadhaar/UID/VID label nearby (English or the Devanagari
# आधार), OR the canonical UIDAI 4-4-4 spaced print grouping (which customer IDs / account numbers do not
# use). ``aadhaa?r`` covers both the "aadhaar" and "aadhar" spellings.
_AADHAAR_CONTEXT_RE = re.compile(r"aadhaa?r|uidai|\buid\b|\bvid\b|आधार", re.IGNORECASE)
_AADHAAR_SPACED_RE = re.compile(r"^[0-9]{4}\s[0-9]{4}\s[0-9]{4}$")
_AADHAAR_CONTEXT_WINDOW = 40  # chars of preceding same-line text scanned for an Aadhaar label


def _has_aadhaar_context(text: str, start: int, matched: str) -> bool:
    """True when a 12-digit run is plausibly an Aadhaar: printed 4-4-4, or labelled as one nearby.

    Deliberately conservative — a number with neither the canonical spacing nor a nearby Aadhaar label
    is NOT run through the checksum, so an ordinary Customer ID can never manufacture a forgery flag.
    """
    if _AADHAAR_SPACED_RE.match(matched.strip()):
        return True
    window = text[max(0, start - _AADHAAR_CONTEXT_WINDOW):start]
    window = window.rsplit("\n", 1)[-1]  # stay on the number's own line — do not read a neighbouring field
    return bool(_AADHAAR_CONTEXT_RE.search(window))


@dataclass(frozen=True)
class ExtractedEntities:
    """Comparable identity fields pulled from one document. ``None`` = not found (never guessed)."""

    pan: str | None = None
    aadhaar: str | None = None              # 12 digits, ONLY if Verhoeff-valid
    aadhaar_invalid: str | None = None      # Aadhaar-shaped but Verhoeff-FAILED (forgery signal)
    ifsc: str | None = None
    account_number: str | None = None
    name: str | None = None                 # normalised, label-anchored
    dob: str | None = None                  # ISO YYYY-MM-DD if parseable

    def comparable_fields(self) -> dict[str, str]:
        """The subset of fields present and usable as cross-document comparison keys."""
        out: dict[str, str] = {}
        if self.pan:
            out["pan"] = self.pan
        if self.aadhaar:
            out["aadhaar"] = self.aadhaar
        if self.ifsc:
            out["ifsc"] = self.ifsc
        if self.account_number:
            out["account_number"] = self.account_number
        if self.name:
            out["name"] = self.name
        if self.dob:
            out["dob"] = self.dob
        return out


def normalise_name(raw: str) -> str | None:
    """Upper-case, strip titles/trailing labels/punctuation, collapse whitespace. ``None`` if empty."""
    s = raw.strip()
    s = _NAME_TRAILING.sub("", s)
    s = _NAME_TITLES.sub("", s)
    s = re.sub(r"[^A-Za-z\s]", " ", s)
    s = re.sub(r"\s+", " ", s).strip().upper()
    return s or None


def _normalise_dob(raw: str) -> str | None:
    """Parse a dd/mm/yyyy (or yyyy/mm/dd) date to ISO. Two-digit years -> 19xx/20xx by a 30-cutoff."""
    parts = re.split(r"[\s./-]+", raw.strip())
    if len(parts) != 3:
        return None
    try:
        nums = [int(p) for p in parts]
    except ValueError:
        return None
    if nums[0] > 31:  # yyyy mm dd
        y, m, d = nums
    else:             # dd mm yyyy
        d, m, y = nums
    if y < 100:
        y += 1900 if y >= 30 else 2000
    if not (1 <= m <= 12 and 1 <= d <= 31 and 1900 <= y <= 2100):
        return None
    return f"{y:04d}-{m:02d}-{d:02d}"


def extract_entities(text: str) -> ExtractedEntities:
    """Extract comparable identity fields from a document's text. Pure + deterministic."""
    if not text:
        return ExtractedEntities()
    upper = text.upper()

    pan_m = _PAN_RE.search(upper)
    ifsc_m = _IFSC_RE.search(upper)

    aadhaar = aadhaar_invalid = None
    for m in _AADHAAR_RE.finditer(text):
        raw_match = m.group(1)
        digits = re.sub(r"\s", "", raw_match)
        if len(digits) != 12:
            continue
        # Context gate (KNOWN_ISSUES #5.2): only a number that actually looks/reads like an Aadhaar is
        # routed through the UIDAI checksum — a bare Customer ID / account number is skipped entirely.
        if not _has_aadhaar_context(text, m.start(), raw_match):
            continue
        if verhoeff_validate(digits):
            aadhaar = digits
            break
        if aadhaar_invalid is None:
            aadhaar_invalid = digits  # keep the first shape-valid-but-checksum-failed candidate

    account = None
    acc_m = _ACCOUNT_RE.search(text)
    if acc_m:
        account = re.sub(r"[\s-]", "", acc_m.group(1))

    name = None
    name_m = _NAME_RE.search(text)
    if name_m:
        name = normalise_name(name_m.group(1))

    dob = None
    dob_m = _DOB_RE.search(text)
    if dob_m:
        dob = _normalise_dob(dob_m.group(1))

    return ExtractedEntities(
        pan=pan_m.group(1) if pan_m else None,
        aadhaar=aadhaar,
        aadhaar_invalid=aadhaar_invalid,
        ifsc=ifsc_m.group(1) if ifsc_m else None,
        account_number=account,
        name=name,
        dob=dob,
    )


def text_from_ocr_words(words: list[dict]) -> str:
    """Reconstruct line-broken text from the canonical ``ctx.shared['ocr']`` word list."""
    if not words:
        return ""
    lines: dict[tuple, list[tuple]] = {}
    for w in words:
        key = (w.get("block_num", 0), w.get("line_num", 0))
        lines.setdefault(key, []).append((w.get("left", 0), str(w.get("text", ""))))
    out: list[str] = []
    for key in sorted(lines):
        toks = [t for _, t in sorted(lines[key]) if t]
        if toks:
            out.append(" ".join(toks))
    return "\n".join(out)


def _pan_confirmed_on_page(ctx: AnalysisContext, pan_claim) -> bool:
    """Independently confirm a VLM-claimed PAN is actually printed on its source page.

    PAN's ontology type is ``"validated"`` (format-only) — unlike a numeric ``Money`` claim, ``builder.py``
    never box-grounds or cross-reads it (ADR-004 §5.2 only covers ``cross_read_critical`` types). Left
    unconfirmed, a VLM's freeform "pan" field would drive :class:`ClaimedIdentityAnalyzer`'s high-stakes
    identity-mismatch accusation purely on the model's say-so — exactly the hallucination-laundering
    CLAUDE.md §3.1/§5.3 forbids for a claim this consequential. This re-reads the claim's own source
    page's real text (PyMuPDF — the same deterministic decode the Money cross-read uses) and requires
    the claimed string to actually be printed there. Fails closed (not confirmed) on any parsing problem,
    a locked/unreadable page, or a non-PDF file — an unconfirmed identity claim is never trusted.
    """
    if not ctx.file_bytes or not is_pdf(ctx.file_bytes):
        return False
    try:
        import pymupdf

        doc = pymupdf.open(stream=ctx.file_bytes, filetype="pdf")
    except Exception:  # noqa: BLE001 — any decode failure fails closed (not confirmed)
        return False
    try:
        if doc.needs_pass and not (ctx.pdf_password and doc.authenticate(ctx.pdf_password)):
            return False
        page_index = pan_claim.provenance.page if pan_claim.provenance else 0
        if not (0 <= page_index < doc.page_count):
            return False
        page_text = doc.load_page(page_index).get_text("text") or ""
    except Exception:  # noqa: BLE001 — a render failure fails closed (not confirmed), never crashes
        return False
    finally:
        doc.close()
    needle = re.sub(r"\s", "", pan_claim.value or "").upper()
    haystack = re.sub(r"\s", "", page_text).upper()
    return bool(needle) and needle in haystack


class EntityExtractionAnalyzer:
    """FILE-mode foundation analyzer: publish ``ctx.shared['entities']`` for the cross-document graph.

    Like the OCR bridge, extraction is NOT a judgment, so this analyzer's own signal is always
    ``NOT_EVALUATED`` (with the extracted field names as measurements) — it never scores a document on
    its own. The cross-document consistency verdict is produced at the *bundle* level
    (``forensics/cross_document.py``), where more than one document's entities exist to compare.
    """

    name = "entity_extraction"
    layer = 3
    mode = Mode.FILE
    order = 45  # after OCR (document_parse, order 5) so ctx.shared['ocr'] exists

    def applicable(self, ctx: AnalysisContext) -> bool:
        return ctx.intake_mode == Mode.FILE

    def analyze(self, ctx: AnalysisContext) -> LayerSignal:
        words = ctx.shared.get("ocr")
        text = text_from_ocr_words(words) if isinstance(words, list) else ""
        if not text and ctx.file_bytes:
            # Text-based PDFs may not have gone through the raster OCR path; this stays best-effort.
            text = ctx.shared.get("page_text", "") or ""
        entities = extract_entities(text)
        
        # Supplement regex entities with VLM extracted claims if available (ADR-004 identity fallback)
        cg = ctx.shared.get("claim_graph")
        if cg:
            # Prefer the VLM's holder_name/name reading over the OCR-regex one whenever the VLM ran —
            # NOT just when OCR found nothing. Tesseract's segmentation-based character recognition is
            # prone to a well-documented ligature confusion on printed names ("rn" merging into what
            # reads as "m" — e.g. a real "KARNALA" misread as "KAMALA"); a vision-language model reads
            # the glyphs holistically and is measurably more reliable for this specific failure mode.
            # Bounded, honest trade: "name" is a SOFT corroborator only (cross_document.py clamps any
            # name disagreement to the REVIEW band and it can never single-handedly reject or approve),
            # so preferring the VLM's read here cannot manufacture a false hard verdict either way — it
            # only changes which spelling a human reviewer sees. (Numeric claims stay OCR-cross-read
            # against the VLM per CLAUDE.md §3.1; this does not change that discipline.)
            name_claim = cg.first("holder_name") or cg.first("name")
            if name_claim and name_claim.value:
                vlm_name = normalise_name(name_claim.value)
                if vlm_name:
                    # Apply the same normalisation so the cross-document matching works identically
                    entities = ExtractedEntities(
                        pan=entities.pan, aadhaar=entities.aadhaar, aadhaar_invalid=entities.aadhaar_invalid,
                        ifsc=entities.ifsc, account_number=entities.account_number,
                        name=vlm_name,
                        dob=entities.dob
                    )
            # We could do the same for PAN/DOB if needed, but the bug specifically requested holder_name.
            if not entities.dob:
                dob_claim = cg.first("date_of_birth") or cg.first("dob")
                if dob_claim and dob_claim.value:
                    entities = ExtractedEntities(
                        pan=entities.pan, aadhaar=entities.aadhaar, aadhaar_invalid=entities.aadhaar_invalid,
                        ifsc=entities.ifsc, account_number=entities.account_number,
                        name=entities.name,
                        dob=_normalise_dob(dob_claim.value) or entities.dob
                    )
            if not entities.pan:
                pan_claim = cg.first("pan")
                # Unlike name/dob (soft corroborators only), PAN feeds a hard identity-mismatch
                # accusation (ClaimedIdentityAnalyzer) — never trust it from the VLM's say-so alone.
                # Two independent gates, both required: (1) the value must actually be PAN-SHAPED —
                # the "pan" predicate is a free-text label the VLM assigns itself (§5.4), and it can
                # mislabel an unrelated printed value (observed: a customer's phone number extracted
                # under predicate="pan") — a page-presence check alone would wrongly confirm it, since
                # the phone number really is printed on the page, just not as a PAN; (2) the value must
                # be independently confirmed as actually printed on its claimed source page.
                pan_value = (pan_claim.value or "").strip().upper() if pan_claim else ""
                if pan_claim and _PAN_RE.fullmatch(pan_value) and _pan_confirmed_on_page(ctx, pan_claim):
                    entities = ExtractedEntities(
                        pan=pan_claim.value.upper(), aadhaar=entities.aadhaar,
                        aadhaar_invalid=entities.aadhaar_invalid,
                        ifsc=entities.ifsc, account_number=entities.account_number,
                        name=entities.name,
                        dob=entities.dob
                    )

        ctx.shared["entities"] = entities
        present = list(entities.comparable_fields().keys())

        # A Verhoeff-FAILED Aadhaar is a real, deterministic forgery tell — surface it as a SCORED
        # signal (not just a measurement, §3.1). It cannot be distinguished from an OCR misread on a
        # single number, so it lands in the REVIEW band (fail-safe), never an auto-reject.
        if entities.aadhaar_invalid:
            return LayerSignal.valid(
                self.name, self.layer, self.mode,
                suspicion=settings.aadhaar_checksum_fail_suspicion,
                weight=settings.weight_id_checksum,
                reason=(f"Aadhaar-format number {entities.aadhaar_invalid!r} FAILS the UIDAI Verhoeff "
                        "checksum — forged number or OCR misread; route to manual review"),
                measurements={"extracted_fields": present, "aadhaar_checksum": "failed"},
            )

        return LayerSignal.not_evaluated(
            self.name, self.layer, self.mode,
            (f"extracted {len(present)} comparable identity field(s): {', '.join(present)}"
             if present else "no comparable identity fields found in this document"),
            extracted_fields=present,
            aadhaar_invalid=False,
        )
